version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST (date_date as TIMESTAMP)"
        description: greenweez raw sales data source
      - name: product
        identifier: raw_gz_product
        description: greenweez raw product data source
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null   
      - name: ship
        identifier: raw_gz_ship
        description: greenweez raw ship data source
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords 
        description: greenweez raw adwords data source

      - name: bing
        identifier: raw_gz_bing
        description: greenweez raw bing data source
      - name: criteo
        identifier: raw_gz_criteo
        description: greenweez raw criteo data source
      - name: facebook
        identifier: raw_gz_facebook
        description: greenweez raw facebook data source

models:
  - name: stg_raw__adwords
    description: testing primary key
    tests:
      - unique:
          column_name: "(campaign_key || '_' || date_date)"
      - not_null:
          column_name: "(campaign_key || '_' || date_date)"
              